### ISSUE TITLE
fail to reproduce the results in Table 2 with Random Prior

### ISSUE THREAD

**Issue by AllenDu01** [tyliu22/Meta-learning-PAC-Bayes-bound-with-data-depedent-prior#1] opened 2021-04-12 23:47 UTC
Dear Tianyu, it is a great honor for me to refer to your paper. But I encounter some problems when reproducing the results in Table 2 with the released code. The details are as below:

(1) Under the 'Permuted Labels' setting,  I run the code to minimize the objectives based on McAllester's, Seeger's , and Variational Bayes's bounds with Random Prior, and the obtained test errors are: 14.4%, 43.1%, 24.9% respectively. However the corresponding test errors reported in Table 2 of the paper are: 42.62%, 54.83%, 48.75%. The gap between the former and the latter seems somewhat big. Could you please explain it?

(2) Meanwhile, will it seem a little strange to get so high test error (over 20%) under the permuted labels setting? I also run the similar code released in https://github.com/ron-amit/meta-learning-adjusting-priors2 (with random prior), but can achieve a low test error (1%) with Seeger's bound as minimization objective.

(3) Back to this repository. I also run the code under the Shuffled Pixels setting with random prior. The test errors of McAllester, Seeger, Variational Bayes are 24.4%, 52.7%, 35.7% respectively, but the reported results in Table 2 are 2.54%, 2.83, and 2.43%, which are much lower than the reproduced ones. Could you please help me explain this results? Thanks very much.

I run all the code as the instruction suggests.

**Comment by tyliu22** [comment] 2022-02-08 11:45
I am sorry for the LATE reply. This GitHub account links to my another mailbox, and I rarely check those emails. 

(1), In this code, author didn't set the Random Seed in our code, so you may not get the same experiment results as reported in our paper. For the PAC-Bayes meta leaning theory, under the 'Permuted Labels' setting, the test error may varies significantly with noises. In the Amit & Meir (2018), under the 'Permuted Labels' setting, the test error is also very high sometimes. Our code is implemented based on Amit & Meir (2018) source code, and I found our proposed algorithms also performed unstable accuracy.

(2), We implement our model based on the code of [meta-learning-adjusting-priors](https://github.com/ron-amit/meta-learning-adjusting-priors), which is the **first version of Amit & Meir** (2018)' code. They updated their **second version** code which is released in [(https://github.com/ron-amit/meta-learning-adjusting-priors2)](https://github.com/ron-amit/meta-learning-adjusting-priors2) (with random prior). Therefore if you want to further develop the PAC-Bayes meta learning bound, one can conduct your experiment on the second version code.

In the Amit & Meir (2018) and our paper, we all met the same problem. The proposed PAC-Bayes bound got high test error under the permuted labels. Unfortunatelly I actually have not idea about it ,and I am not sure if it‘s caused by the code implement or the convergence performance. 

(3), We conduct our experiments on MNIST, which is a very simple dataset. All the PAC-Bayes meta learning theories perform well under the Shuffled Pixels setting.  Therefore one can check the hyper-parameters setting and re-run our experiments.

if you have any problems, please don't hesitate to contact me.My email address: tianiyu.liu-1@student.uts.edu.au




Public

If you have any another question, please don't hesitate to contact me via tianyu.liu-1@student.uts.edu.au

**Closed as completed** 2022-06-07 00:42 UTC
